export const COMMON_BRANCH_FIELD_MAP = {
  etmEntityId: "etmEntityId",
  EtmName: "etmName",
  EtmShortName: "etmShortName",
  authorizationStatus: "authorizationStatus",
  withaffectdate: "withaffectdate",
//   companyEntity: "company",
  // branch: "branch",
  activeDate: "activeDate",
  pincode: "pincode",
  address: "address",
  country: "country",
  state: "state",
  district: "district",
  place: "place",
  email: "email",
  mobileNumber: "mobileNumber",
  landlineNumber: "landlineNumber",
};
