export const COMMON_ENTITY_FIELD_MAP = {
  etmEntityId: "etmEntityId",
  EtmShortName: "etmShortName",
  authorizationStatus: "authorizationStatus",
  withaffectdate: "withaffectdate",
  EtmName: "etmName",
  EtmImage: "companyImagePath",
  activeDate: "activeDate",
  pincode: "pincode",
  address: "address",
  country: "country",
  state: "state",
  district: "district",
  place: "place",
  email: "email",
  mobileNumber: "mobileNumber",
  landlineNumber: "landlineNumber",
  employerName: "employerName",
  employerEmail: "employerEmail",
  employerNumber: "employerNumber",
  designation: "designation",
};
