export const COMMON_COMPANY_FIELD_MAP = {
  companyMstID: "companyMstID",
  shortName: "shortName",
  authorizationStatus: "authorizationStatus",
  withaffectdate: "withaffectdate",
  company: "company",
  companyImage: "companyImagePath",
  activeDate: "activeDate",
  pincode: "pincode",
  address: "address",
  country: "country",
  state: "state",
  district: "district",
  place: "place",
  email: "email",
  mobileNumber: "mobileNumber",
  landlineNumber: "landlineNumber",
  employerName: "employerName",
  employerEmail: "employerEmail",
  employerNumber: "employerNumber",
  designation: "designation",
};
